### ISSUE TITLE
🐛[BUG] 老板我又来了Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION

### ISSUE THREAD

**Issue by ckbkdj** [codyi96/xml2axml#4]
Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION]
步骤
1.反编译xml
2.修改xml字段(我修改的是Application的android:name字段)
3.回编译xml
4.打包的项目中出现无法安装
<查看stringChunk 里面部分String 结尾会多出两位 00 00是否会是这个问题>
<或者是空字符串的编/解码问题导致>

**Comment by ckbkdj** [comment]
![image](https://user-images.githubusercontent.com/9382231/83320307-cbf7a080-a278-11ea-9af9-d2951b95429b.png)
如果apktool 回编译项目回报这个错误

**Comment by ckbkdj** [comment]
> I: 开始回编译 [app-debug.apk]
> I: Using Apktool 2.4.0_0918
> I: Smaling smali folder into classes.dex...
> [Fatal Error] :1:1: 前言中不允许有内容。
> I: Building resources...
> W: D:\Github\jiagu\dexshellerInMemory\app-debug\AndroidManifest.xml:1: error: Error parsing XML: not well-formed (invalid token)
> W:
> brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Mic\AppData\Local\Temp\brut_util_Jar_3985120963331572464.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 29, --version-code, 20200527, --version-name, 1.3.0, --no-version-vectors, -F, C:\Users\Mic\AppData\Local\Temp\APKTOOL8804259715256849442.tmp, -0, arsc, -0, arsc, -I, C:\Users\Mic\AppData\Local\apktool\framework\1.apk, -S, D:\Github\jiagu\dexshellerInMemory\app-debug\res, -M, D:\Github\jiagu\dexshellerInMemory\app-debug\AndroidManifest.xml]

**Comment by codyi96** [comment]
按issue模板重新提交吧
